<?php
defined("__POSEXEC") or die("No direct access allowed!");
__requiredSystem("1.2.3") or die("You need to upgrade the system");
/**
 * PuzzleOS
 * Build your own web-based application
 *
 * @package      maral.puzzleos.core.users
 * @author       Mohammad Ardika Rifqi <rifweb.android@gmail.com>
 * @copyright    2014-2017 MARAL INDUSTRIES
 *
 * @software     Release: 1.1.1
 */

return array(
	"APP_ON_GROUP"		=>	"Mohon merubah aplikasi yang tertaut pada kelompok ini ke kelompok lainnya",
	"SEL_GROUP"			=>	"Pilih kelompok pengguna",
	"GNAME_NO_BLANK"	=>	"Nama kelompok harus diisi",
	"CONFIRM_RM_GROUP"	=>	"Apakah Anda yakin ingin menghapus kelompok ini",
	"YOU_NO_MOVE"		=>	"Anda tidak bisa memindahkan diri Anda sendiri",
	"LEVEL"				=>	"Tingkatan",
	"GROUP_NAME"		=>	"Nama",
	"ADD_UGROUP"		=>	"Tambah kelompok baru",
	"ASSIGN2"			=>	"ke kelompok baru",
	"ASSIGN1"			=>	"Masukkan",
	"FIND_USER"			=>	"Cari pengguna",
	"GROUP_EDITOR"		=>	"Editor Kelompok",
	"LOGIN"				=>	"Masuk",
	"USERNAME"			=>	"Username",
	"PASSWORD"			=>	"Kata Sandi",
	"F_PASS"			=>	"Lupa Password",
	"NH"				=>	"Bantuan",
	"ECEH"				=>	"Masukkan alamat email Anda",
	"RMP"				=>	"Lanjutkan",
	"LIA"				=>	"Masuk sebagai",
	"C_PASS"			=>	"Ganti kata sandi",
	"A_SET"				=>	"Profil",
	"LOGOUT"			=>	"Keluar",
	"OLD_PASS"			=>	"Kata sandi lama",
	"NEW_PASS"			=>	"Kata sandi baru",
	"VER_PASS"			=>	"Verifikasi Kata sandi",
	"NAME"			     =>	"Nama Lengkap",
	"EMAIL"				=>	"Email",
	"PHONE"				=>	"No. Telpon",
	"SAVE_SET"			=>	"Simpan Setelan",
	"DCYP"				=>	"Periksa kembali kata sandi Anda",
	"PASS_CHANGED"		=>	"Kata sandi dirubah",
	"SET_S"				=>	"Setelan disimpan! ",
	"EMAILE"			=>	"Email tidak boleh kosong",
	"LOGGED_OUT"		=>	"Berhasil keluar",
	"CSCE"				=>	"Tidak bisa mengirim email konfirmasi",
	"ECHS"				=>	"Email konfirmasi telah dikirim kepada ",
	"NEHS"				=>	"Email komfirmasi baru sudah dikirim",
	"CYNE"				=>	"Konfirmasi email baru Anda",
	"E10"				=>	"Anda telah melakukan permintaan untuk merubah alamat email Anda menjadi:",
	"E11"				=>	"Untuk melanjutkan, klik ",
	"E12"				=>	"tautan ini",
	"E13"				=>	"di dalam",
	"E14"				=>	"perangkat yang sama",
	"E15"				=>	"dimana Anda membuat permintaan ini. Tautan ini akan kadaluarsa dalam 10 menit sejak email ini dikirim.",
	"E16"				=>	"Jika Anda tidak membuat permintaan ini, abaikan pesan ini.",
	"E_CH"				=>	"Alamat Email telah dirubah",
	"PRLHS"				=>	"Kami telah mengirimkan instruksi selanjutnya ke email Anda",
	"PCYP"				=>	"Mohon ganti kata sandi Anda sebelum melanjutkan",
	"PRR"				=>	"Permintaan Merubah Password",
	"E20"				=>	"Anda telah meminta untuk mendapatkan kata sandi yang baru. Klik disini",
	"PASS_E"			=>	"Kata sandi tidak boleh kosong",
	"PNM"				=>	"Kata sandi tidak sesuai",
	"PLTYA"				=>	"Tolong masuk",
	"NAAWTH"			=>	"Periksa kembali email Anda",
	"DCYC"				=>	"Periksa kembali informasi Anda",
	"CHECK_YOUR_PHONE"	=>	"Periksa kembali nomor telepon Anda",
	"EMAIL_NOT_VALID"	=>	"Format email Anda salah",
	"MANAGE_USERS"		=>	"Kelola Pengguna",
	"ID"				=>	"ID",
	"AUTH"				=>	"Otoritas",
	"LOCALIZATION"		=>	"Lokalisasi",
	"DELETE"			=>	"Hapus",
	"CLICK_TOE"			=>	"Klik untuk merubah",
	"DONOT_CH_SU"		=>	"Jangan rubah otoritas Superuser atau Anda akan kehilangan kendali dari sistem",
	"CH_SAVED"			=>	"Perubahan disimpan",
	"CH_NOT_SAVED"		=>	"Tidak bisa menyimpan perubahan",
	"CHANGED"			=>	"Dirubah",
	"UNCHANGED"			=>	"Tidak berubah",
	"NEW_USER"			=>	"Tambah User",
    "SIGNUP"			=>	"Daftar",
	"SETTINGS"			=> 	"Pengaturan",
	"G-RECAPTCHA"		=> 	"Google Recaptcha",
	"G-RECAPTCHA-WARN"	=> 	"Gunakan Recaptcha",
	"SITEKEY"			=> 	"Site key",
	"SECRETKEY"			=> 	"Secret key",
	"REGISTRATION"		=> 	"Pendaftaran",
	"REQ_ACTIVATE_ACC"	=> 	"Haruskan aktivasi akun",
	"REG_NEW_USER_AS"	=> 	"Daftarkan pengguna baru sebagai",
	"PROFILE_REQ"		=> 	"Kelengkapan Profil",
	"EMAIL_REQ"			=> 	"Email wajib diisi",
	"PHONE_REQ"			=> 	"Nomor telepon wajib diisi",
	"REMEMEMBER_FEAT"	=> 	"Fitur 'Ingat Saya'",
	"ENABLE"			=> 	"Hidupkan",
	"MISC"				=> 	"Lainnya",
	"LOGIN_SESSION_SHARE"=>	"Bagikan sesi login ke subdomain"
);

?>
