<?php
/**
 * PuzzleOS
 * Build your own web-based application
 *
 * @author       Mohammad Ardika Rifqi <rifweb.android@gmail.com>
 * @copyright    2014-2018 MARAL INDUSTRIES
 */

/***********************************
 * DONT CHANGE THIS FILE
 * This file generate the "defines"
 * needed by PuzzleOS to work.
 ***********************************/

defined("__SYSTEM_NAME") or define("__SYSTEM_NAME", "PuzzleOS");
define("__POS_VERSION", "2.1.11");

/**
 * Return /path/to/qualified/root/directory
 */
define("__ROOTDIR", str_replace("\\", "/", dirname(__DIR__)));

/**
 * Return the name of public directory generated by index.php
 * Usually it's "public" or "public_html"
 */
defined("__PUBLICDIR") or define("__PUBLICDIR", "public");

/**
 * Return something.com 
 */
define("__HTTP_HOST", $_SERVER["HTTP_HOST"]);

/**
 * Return "https://" or "http://"
 */
define("__HTTP_PROTOCOL", (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://");

/**
 * Return http://something.com
 */
define("__SITEURL", __HTTP_PROTOCOL . $_SERVER['HTTP_HOST'] . str_replace("/index.php", "", $_SERVER["SCRIPT_NAME"]));

/**
 * Return applications/yourapp/assets/base_1.gif?my=you
 */
define("__HTTP_REQUEST", ltrim(str_replace(__SITEURL, "", str_replace(str_replace("/index.php", "", $_SERVER["SCRIPT_NAME"]), "", $_SERVER['REQUEST_URI'])), "/"));

/**
 * Return applications/yourapp/assets/base_1.gif
 */
define("__HTTP_URI", explode("?", __HTTP_REQUEST)[0]);

define("APP_DEFAULT", 1);
define("APP_NOT_DEFAULT", 0);
define("APP_CANNOT_DEFAULT", 3);

define("T_DAY", 86400);
define("T_HOUR", 3600);
define("T_MINUTE", 60);
define("TODAY", strtotime(date("Y/m/d", time())));

define("__WORKERDIR", __ROOTDIR . "/storage/worker");
