#!/usr/bin/env php
<?php
/**
 * PuzzleOS
 * Build your own web-based application
 *
 * @author       Mohammad Ardika Rifqi <rifweb.android@gmail.com>
 * @copyright    2014-2020 MARAL INDUSTRIES
 */

define('__POSEXEC', 1);
define('__POSWORKER', 1);

require('bootstrap/boot.php');

// Run the worker
Worker::do($argv);
