<?php
defined("__POSEXEC") or die("No direct access allowed!");
__requiredSystem("1.2.2") or die("You need to upgrade the system");
/**
 * PuzzleOS
 * Build your own web-based application
 * 
 * @package      maral.puzzleos.core.admin
 * @author       Mohammad Ardika Rifqi <rifweb.android@gmail.com>
 * @copyright    2014-2017 MARAL INDUSTRIES
 * 
 * @software     Release: 1.1.1
 */

return array(
	"TURN_OFF"					=> "Matikan",
	"TURN_ON"					=> "Nyalakan",
	"RND"						=> "Daftarkan domain baru",
	"MANAGING"					=> "SEDANG MENGELOLA",
	"DEF_APP_USED"				=> "Salah satu aplikasi masih menjadi halaman utama",
	"DEF_TMPL_USED"				=> "Salah satu template masih dipakai",
	"ERROR_REPORTING"			=> "Laporan Error",
	"ERROR"						=> "Kesalahan",
	"INFO"						=> "Informasi",
	"WARNING"					=> "Peringatan",
	"SUCCESS"					=> "Berhasil",
	"DEBUG_MODE"				=> "Mode Penelitian",
	"NORMAL_REPORT"				=> "Mode Normal",
	"NONE"						=> "Matikan laporan",
	"INFO1"						=> "Tampilkan semua error. Termasuk pesan error yang tidak dibutuhkan.",
	"INFO2"						=> "Tampilkan kesalahan normal dan kesalahan fatal.",
	"INFO3"						=> "Tidak ada laporan error.",
	"DATABASE"					=> "Basis Data",
	"INFO4"						=> "Jangan pernah mengakses tempat ini jika anda tidak tahu apa yang anda lakukan.",
	"USERNAME"					=> "Nama User",
	"NO_PASSWORD"				=> "Tidak ada password",
	"UNCHANGED"					=> "Password tidak berubah",
	"HOST"						=> "Server",
	"ADDITIONAL_OPTIONS"		=> "Opsi Tambahan",
	"SITE_NAME"					=> "Nama Situs",
	"SITE_URL"					=> "URL Situs",
	"ROOT_DIRECTORY"			=> "Folder Root",
	"COPYRIGHT"					=> "Teks hak cipta",
	"META_DESCRIPTION"			=> "Deskripsi Meta",
	"MAILER_OPTIONS"			=> "Opsi E-mail",
	"EMAIL_FROM"				=> "Alamat email pengirim",
	"EMAIL_NAME"				=> "Nama email pengirim",
	"LANG_AVAILABILITY"			=> "Ketersediaan lokalisasi",
	"ADD_LANG"					=> "Tambah lokalisasi",
	"NO_LANGUAGE_SELECTED"		=> "Tidak ada lokalisasi yang dipilih!",
	"INSTALL_PACKAGE"			=> "Pasang Puzzle",
	"PACKAGE_MUST_BE_IN"		=> "Puzzle harus berbentuk",
	"OTHERWISE_CANNOT_INSTALL"	=> "Jika tidak, Puzzle tidak bisa dipasang.",
	"FORCE_INSTALL"				=> "Paksa pemasangan Puzzle yang tidak terverifikasi",
	"RISK_YOURS"				=> "Risiko menjadi milik anda.",
	"INSTALL"					=> "Pasang",
	"UNINSTALL_PACKAGE"			=> "Hapus Puzzle",
	"SAVE_THOSE_SETTINGS"		=> "Simpan semua setelan?",
	"SAVE"						=> "Simpan",
	"SAVE_ON"					=> "Simpan di",
	"ROLLBACK"					=> "Kembalikan setelan",
	"UNSIGNED_PKG_MAY_VIRUS"	=> "Puzzle tidak terverifikasi mungkin mengandung virus atau konten yang tidak diinginkan.",
	"UNEXPECTED_ROLL_BACK"		=> "Terjadi sebuah kesalahan saat pemasangan. Mengembalikan ulang...",
	"PACKAGE_LASTEST"			=> "Puzzle telah dipasang dengan versi yang lebih baru",
	"PACKAGE_SIGN_FALSE"		=> "Puzzle tidak diverifikasi dengan benar",
	"PACKAGE_NO_INSTALLER"		=> "Tidak ada file installer di dalam Puzzle",
	"PACKAGE_CANNOT_EXTRACT"	=> "Tidak dapat mengekstrak Puzzle",
	"PACKAGE_CANNOT_OPEN"		=> "Tidak bisa membuka Puzzle",
	"CONFIGURATION_UPDATED"		=> "Pengaturan telah diperbarui!",
	"PACKAGE_INSTALLED"			=> "Puzzle telah dipasang!",
	"PACKAGE_UNINSTALLED"		=> "Puzzle berhasil di hapus!",
	"ACTION_FAILED"				=> "Aksi gagal!",
	"PACKAGE_CANNOT_PARSE"		=> "Tidak dapat menerjemahkan file installer!",
	"SET_AS_DEFAULT"			=> "Jadikan halaman utama",
	"NOT_AVAILABLE"				=> "Tidak tersedia",
	"CURRENTLY_DEFAULT"			=> "Menjadi halaman utama",
	"MANAGE"					=> "Kelola",
	"NO_APPS"					=> "Tidak ada aplikasi yang dapat di kelola",
	"UNINSTALL_THIS_PKG"		=> "Hapus Puzzle ini?",
	"VERSION_LOW"				=> "Lakukan upgrade sistem sebelum memasang Puzzle ini",
	"SMTP_NO_ENC"				=> "Open",
	"USE_SMTP_AUTH"				=> "Gunakan autentikasi SMTP",
	"USE_SMTP_EN"				=> "Gunakan SMTP untuk mengirim email",
	"PORT"						=> "Port",
	"EMAIL_TEST"				=> "Coba kirim email!",
	"SMTP_OPTION"				=> "Pengaturan SMTP",
	"INSTALL_LANG"				=> "Pasang",
	"REMOVE_LANG"				=> "Hapus",
	"NO_PUZZLE"					=> "Tidak ada Puzzle",
	"MDOMAIN"					=> "Opsi Multi-domain",
	"MDOMAIN_ASK"				=> "Izinkan PuzzleOS untuk menyajikan website di berbagai domain",
)
?>